apiVersion: aws.90poe.io/v1alpha1
kind: GlueJob
metadata:
  labels:
    app.kubernetes.io/name: gluejob
    app.kubernetes.io/instance: gluejob-sample
    app.kubernetes.io/created-by: glue-jobs-operator
  name: gluejob-sample
  namespace: infra
spec:
  # TODO(user): Add fields here
  name: sarunas-test-glue-job
  command:
    name: first
    scriptLocation: s3://90poe-glue-jobs/some/job.py
  role: arn:aws:iam::504106747086:role/90poe-aws-glue-service-role-20230306134050765500000001
  defaultArguments:
    "--ENV_PREFIX": "dev"
