apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "glue-jobs-operator.labels" . | nindent 4 }}
    {{- with .Values.operator.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "glue-jobs-operator.fullname" . }}
rules:
- apiGroups:
  - aws.90poe.io
  resources:
  - gluejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.90poe.io
  resources:
  - gluejobs/finalizers
  verbs:
  - update
- apiGroups:
  - aws.90poe.io
  resources:
  - gluejobs/status
  verbs:
  - get
  - patch
  - update
