{{- $sm := .Values.serviceMonitor }}
{{- if or $sm.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "glue-jobs-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: glue-jobs-operator
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "glue-jobs-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    port: {{ .Values.operator.metricsPort | quote }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: glue-jobs-operator
{{- end }}